### ISSUE TITLE
the problem with trading the ETHONE/MO pair

### ISSUE THREAD

**Issue by PVA1987** [TeaPartyCrypto/Tea#12]
1) I have two metamask accounts that are on different machines.
2) I am creating a MO/ETHONE pair. sell MO for ETH
0x671865C6175025723E22169fdb7133e71A2833bf - buyer
0x2B12ed8A31244e50457818FC695a4FF43D245997 - seller
3) I connect accounts to the application and pay a commission of 1 MO with each account. 
4) I waited until the transaction for the commission passes through both wallets
5) the seller creates an order of 0.1MO for 0.1ETH. 
Shipping Addresses and Return Shipping Address I specify the address of the seller's metamask
6) the buyer sees in his application an order to sell MO for ETH (Order: ed640e20-8fce-4c81-9e3e-bae6644ad2a1)
7) The buyer enters into his address in 2 fields, presses the buy button
8) The escrow addresses for the buyer and seller have been received
`!!!! I got to this part. it confuses me that the sell order was in MO/ETHONE. but both the seller and the buyer receive an intermediate wallet in the MO network`
9) The seller sends MO to the middle address 0xb9b9E09eCDdf8721d6941171037B11bBf6FC6642
The buyer sends ETHONE to the middle address 0x5b4526E78bcCd34e246c0cBF6fE38021daA69920
`Private keys do not appear.... I try to send MO instead of ETHONE at the buyer's place`

10) After sending the MO, there were also no private keys from escrow wallets

**Comment by JeffNeff** [comment]
Please Clear your Browser cache. This will solve the problem .

**Comment by JeffNeff** [comment]
Thank you for posting the issue!
